# MongoDB

Based on https://docs.mongodb.com/getting-started

MongoDB is a **NoSQL** open-source **document database**.  MongoDB provides horizontal scaling by replicating and partitioning the data over multiple nodes. This can improve the reliability and scalability of the system.

A record in MongoDB is a **document**, which is a data structure composed of field and value pairs. MongoDB documents are similar to JSON objects or Python dictionaries. The values of fields may include other documents, arrays, and arrays of documents.

This is an example of a document:
```JSON
{
   "_id" : ObjectId("54c955492b7c8eb21818bd09"),
   "address" : {
      "street" : "2 Avenue",
      "zipcode" : "10075",
      "building" : "1480",
      "coord" : [ -73.9557413, 40.7720266 ]
   },
   "borough" : "Manhattan",
   "cuisine" : "Italian",
   "grades" : [
      {
         "date" : ISODate("2014-10-01T00:00:00Z"),
         "grade" : "A",
         "score" : 11
      },
      {
         "date" : ISODate("2014-01-16T00:00:00Z"),
         "grade" : "B",
         "score" : 17
      }
   ],
   "name" : "Vella",
   "restaurant_id" : "41704620"
}
```
In MongoDB, documents have a unique **_id** field that acts as a primary key. MongoDB automatically adds a unique _id to each document if you are not providing it by yourself.

MongoDB stores documents in **collections**. Collections are analogous to tables in relational databases. Unlike a table, however, a collection does not require its documents to have the same schema.

You can start a Docker image with MongoDB like this:
```bash
docker run -p 27017:27017 -d mongo
```

In production you really (!) would need to enable authentication with username and password, but for development purposes this is fine.

In [4]:
# Install the pymongo Python Package 
#!pip3 install pymongo

In [5]:
from pymongo import MongoClient
from pprint import pprint
import requests

Use MongoClient to create a connection. If you do not specify any arguments to MongoClient, then MongoClient defaults to the MongoDB instance that runs on the localhost interface on port 27017. You can also specify a complete MongoDB URI to define the connection, including explicitly specifying the host and port number. For example, the following creates a connection to a MongoDB instance that runs on mongodb0.example.net and the port of 27017: client = MongoClient("mongodb://mongodb0.example.net:27017")

In [6]:
# Client connects to "localhost" by default 
client = MongoClient()

The first fundamental class of objects you will interact with using pymongo is Database which represents the database construct in MongoDB. Databases hold groups of logically related collections. MongoDB creates new databases implicitly upon their first use. Connect (create) with a database of your name, e.g. 

```python
db = client["rolandmueller"]
``` 
or 

```python
db = client.rolandmueller
```

In [7]:
# Create local "bipm" database on the fly 
db = client['bipm']

In [8]:
# When we rerun the whole notebook, we start from scratch 
# by dropping the colection "courses"
db.courses.drop()

In [9]:
# Create a Python Dictonary
courses = [
    {'title': 'Data Science',
     'lecturer': {
         'name': 'Markus Löcher',
         'department': 'Math',
         'status': 'Professor'
     },
     'semester': 1},
    {'title': 'Data Warehousing',
     'lecturer': {
         'name': 'Roland M. Mueller',
         'department': 'Information Systems',
         'status': 'Professor'
     },
     'semester': 1},
    {'title': 'Business Process Management',
     'lecturer': {
         'name': 'Frank Habermann',
         'department': 'Information Systems',
         'status': 'Professor'
     },
     'semester': 1},
    {'title': 'Stratigic Issues of IT',
     'lecturer': {
         'name': 'Sven Pohland',
         'department': 'Information Systems',
         'status': 'Professor'
     },
     'semester': 1},
    {'title': 'Text, Web and Social Media Analytics Lab',
     'lecturer': {
         'name': 'Markus Löcher',
         'department': 'Math',
         'status': 'Professor'
     },
     'semester': 2},
    {'title': 'Enterprise Architectures for Big Data',
     'lecturer': {
         'name': 'Roland M. Mueller',
         'department': 'Information Systems',
         'status': 'Professor'
     },
     'semester': 2},
    {'title': 'Business Process Integration Lab',
     'lecturer': {
         'name': 'Frank Habermann',
         'department': 'Information Systems',
         'status': 'Professor'
     },
     'semester': 2},
    {'title': 'IT-Security and Privacy',
     'lecturer': {
         'name': 'Dennis Uckel',
         'department': 'Information Systems',
         'status': 'External'
     },
     'semester': 2},
    {'title': 'Research Methods',
     'lecturer': {
         'name': 'Marcus Birkenkrahe',
         'department': 'Information Systems',
         'status': 'Professor'
     },
     'semester': 2},
]

In [10]:
pprint(courses)

[{'lecturer': {'department': 'Math',
               'name': 'Markus Löcher',
               'status': 'Professor'},
  'semester': 1,
  'title': 'Data Science'},
 {'lecturer': {'department': 'Information Systems',
               'name': 'Roland M. Mueller',
               'status': 'Professor'},
  'semester': 1,
  'title': 'Data Warehousing'},
 {'lecturer': {'department': 'Information Systems',
               'name': 'Frank Habermann',
               'status': 'Professor'},
  'semester': 1,
  'title': 'Business Process Management'},
 {'lecturer': {'department': 'Information Systems',
               'name': 'Sven Pohland',
               'status': 'Professor'},
  'semester': 1,
  'title': 'Stratigic Issues of IT'},
 {'lecturer': {'department': 'Math',
               'name': 'Markus Löcher',
               'status': 'Professor'},
  'semester': 2,
  'title': 'Text, Web and Social Media Analytics Lab'},
 {'lecturer': {'department': 'Information Systems',
               'name': 'Roland M. Mueller',
               'status': 'Professor'},
  'semester': 2,
  'title': 'Enterprise Architectures for Big Data'},
 {'lecturer': {'department': 'Information Systems',
               'name': 'Frank Habermann',
               'status': 'Professor'},
  'semester': 2,
  'title': 'Business Process Integration Lab'},
 {'lecturer': {'department': 'Information Systems',
               'name': 'Dennis Uckel',
               'status': 'External'},
  'semester': 2,
  'title': 'IT-Security and Privacy'},
 {'lecturer': {'department': 'Information Systems',
               'name': 'Marcus Birkenkrahe',
               'status': 'Professor'},
  'semester': 2,
  'title': 'Research Methods'}]

## insert_many()

You can use the `insert_one()` method and the `insert_many()` method to add documents to a collection in MongoDB. If you attempt to add documents to a collection that does not exist, MongoDB will create the collection for you.

In [11]:
db.courses.insert_many(courses)

## find()

You can use the find() method to issue a query to retrieve data from a collection in MongoDB. All queries in MongoDB have the scope of a single collection.
Queries can return all documents in a collection or only the documents that match a specified filter or criteria. You can specify the filter or criteria in a document and pass as a parameter to the find() method. With no parameter, find() returns all documents in the collection.

The find() method returns query results in a cursor, which is an iterable object that yields documents. Then you can print all documents.

```python
cursor = db.my_collection.find()

for document in cursor:
    pprint(document)
```

In [12]:
# TODO: Print all courses
cursor = db.courses.find()
for document in cursor:
    pprint(document)

{'_id': ObjectId('628e4facb49f753ffdf81da5'),
 'lecturer': {'department': 'Math',
              'name': 'Markus Löcher',
              'status': 'Professor'},
 'semester': 1,
 'title': 'Data Science'}
{'_id': ObjectId('628e4facb49f753ffdf81da6'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Roland M. Mueller',
              'status': 'Professor'},
 'semester': 1,
 'title': 'Data Warehousing'}
{'_id': ObjectId('628e4facb49f753ffdf81da7'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Frank Habermann',
              'status': 'Professor'},
 'semester': 1,
 'title': 'Business Process Management'}
{'_id': ObjectId('628e4facb49f753ffdf81da8'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Sven Pohland',
              'status': 'Professor'},
 'semester': 1,
 'title': 'Stratigic Issues of IT'}
{'_id': ObjectId('628e4facb49f753ffdf81da9'),
 'lecturer': {'department': 'Math',
              'name': 'Markus Löcher',
              'status': 'Professor'},
 'semester': 2,
 'title': 'Text, Web and Social Media Analytics Lab'}
{'_id': ObjectId('628e4facb49f753ffdf81daa'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Roland M. Mueller',
              'status': 'Professor'},
 'semester': 2,
 'title': 'Enterprise Architectures for Big Data'}
{'_id': ObjectId('628e4facb49f753ffdf81dab'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Frank Habermann',
              'status': 'Professor'},
 'semester': 2,
 'title': 'Business Process Integration Lab'}
{'_id': ObjectId('628e4facb49f753ffdf81dac'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Dennis Uckel',
              'status': 'External'},
 'semester': 2,
 'title': 'IT-Security and Privacy'}
{'_id': ObjectId('628e4facb49f753ffdf81dad'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Marcus Birkenkrahe',
              'status': 'Professor'},
 'semester': 2,
 'title': 'Research Methods'}

## JSON

You can store a JSON document if you convert it before to a Python dictionary:

In [13]:
import json

In [14]:
my_json = '{"title": "Master Thesis", "semester": 3}'
another_course = json.loads(my_json)
another_course

{'title': 'Master Thesis', 'semester': 3}

## insert_one()

The `insert_one()` method adds the document into the collection.

In [15]:
# TODO: Store `another_course` as another course:
db.courses.insert_one({'title': 'another_course'})

In [16]:
# TODO: Print all courses
cursor = db.courses.find()
for document in cursor:
    pprint(document)

{'_id': ObjectId('628e4facb49f753ffdf81da5'),
 'lecturer': {'department': 'Math',
              'name': 'Markus Löcher',
              'status': 'Professor'},
 'semester': 1,
 'title': 'Data Science'}
{'_id': ObjectId('628e4facb49f753ffdf81da6'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Roland M. Mueller',
              'status': 'Professor'},
 'semester': 1,
 'title': 'Data Warehousing'}
{'_id': ObjectId('628e4facb49f753ffdf81da7'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Frank Habermann',
              'status': 'Professor'},
 'semester': 1,
 'title': 'Business Process Management'}
{'_id': ObjectId('628e4facb49f753ffdf81da8'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Sven Pohland',
              'status': 'Professor'},
 'semester': 1,
 'title': 'Stratigic Issues of IT'}
{'_id': ObjectId('628e4facb49f753ffdf81da9'),
 'lecturer': {'department': 'Math',
              'name': 'Markus Löcher',
              'status': 'Professor'},
 'semester': 2,
 'title': 'Text, Web and Social Media Analytics Lab'}
{'_id': ObjectId('628e4facb49f753ffdf81daa'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Roland M. Mueller',
              'status': 'Professor'},
 'semester': 2,
 'title': 'Enterprise Architectures for Big Data'}
{'_id': ObjectId('628e4facb49f753ffdf81dab'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Frank Habermann',
              'status': 'Professor'},
 'semester': 2,
 'title': 'Business Process Integration Lab'}
{'_id': ObjectId('628e4facb49f753ffdf81dac'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Dennis Uckel',
              'status': 'External'},
 'semester': 2,
 'title': 'IT-Security and Privacy'}
{'_id': ObjectId('628e4facb49f753ffdf81dad'),
 'lecturer': {'department': 'Information Systems',
              'name': 'Marcus Birkenkrahe',
              'status': 'Professor'},
 'semester': 2,
 'title': 'Research Methods'}
{'_id': ObjectId('628e4facb49f753ffdf81dae'), 'title': 'another_course'}

## find_one() and find()

`find_one()` returns the first match. ```find()```returns all matches.

The query condition for `find_one()` and `find()` for an equality match on fields has the following form:
```python
{ <field1>: <value1>, <field2>: <value2>, ... } 
```

The following operation finds the first documents whose name field equals "Manhattan".

```python
cursor = db.restaurants.find_one({"name": "Manhattan"})
```

In [17]:
# TODO: Find the course with the title "Data Science" 
# save the result in a varibale result
# and pprint the result.
db.courses.find_one({'title': 'Data Science'})

{'_id': ObjectId('628e4facb49f753ffdf81da5'),
 'title': 'Data Science',
 'lecturer': {'name': 'Markus Löcher',
  'department': 'Math',
  'status': 'Professor'},
 'semester': 1}

In [18]:
#print(result["_id"])
#print(result["lecturer"]["name"])

In [19]:
# TODO: Find the first course (one course) in the second semester
# and print it
pprint(db.courses.find_one({'semester': 2}))

{'_id': ObjectId('628e4facb49f753ffdf81da9'),
 'lecturer': {'department': 'Math',
              'name': 'Markus Löcher',
              'status': 'Professor'},
 'semester': 2,
 'title': 'Text, Web and Social Media Analytics Lab'}

In [20]:
# TODO: Find all courses in the second semester
# and print the course titles

cursor = db.courses.find({'semester': 2}, {'title'})
for document in cursor:
    pprint(document)

{'_id': ObjectId('628e4facb49f753ffdf81da9'),
 'title': 'Text, Web and Social Media Analytics Lab'}
{'_id': ObjectId('628e4facb49f753ffdf81daa'),
 'title': 'Enterprise Architectures for Big Data'}
{'_id': ObjectId('628e4facb49f753ffdf81dab'),
 'title': 'Business Process Integration Lab'}
{'_id': ObjectId('628e4facb49f753ffdf81dac'),
 'title': 'IT-Security and Privacy'}
{'_id': ObjectId('628e4facb49f753ffdf81dad'), 'title': 'Research Methods'}

In [21]:
# TODO: Find all courses in the second semester
# and print the lecturers names

cursor = db.courses.find({'semester': 2}, {'lecturer.name'})
for document in cursor:
    pprint(document)

{'_id': ObjectId('628e4facb49f753ffdf81da9'),
 'lecturer': {'name': 'Markus Löcher'}}
{'_id': ObjectId('628e4facb49f753ffdf81daa'),
 'lecturer': {'name': 'Roland M. Mueller'}}
{'_id': ObjectId('628e4facb49f753ffdf81dab'),
 'lecturer': {'name': 'Frank Habermann'}}
{'_id': ObjectId('628e4facb49f753ffdf81dac'),
 'lecturer': {'name': 'Dennis Uckel'}}
{'_id': ObjectId('628e4facb49f753ffdf81dad'),
 'lecturer': {'name': 'Marcus Birkenkrahe'}}

## Subelements

Sometimes documents contains embedded documents as its elements. To specify a condition on a field in these documents, use the dot notation. Dot notation requires quotes around the whole dotted field name. The following queries for documents whose grades array contains an embedded document with a field grade equal to "B".

```python
cursor = db.restaurants.find({"grades.grade": "B"})
```

In [25]:
# TODO: Find all courses of Frank Habermann
# and print the title and the semester


cursor = db.courses.find({"lecturer.name":"Frank Habermann"}, {'title',"semester"})
for document in cursor:
    pprint(document)

{'_id': ObjectId('628e4facb49f753ffdf81da7'),
 'semester': 1,
 'title': 'Business Process Management'}
{'_id': ObjectId('628e4facb49f753ffdf81dab'),
 'semester': 2,
 'title': 'Business Process Integration Lab'}

## Logical AND

You can specify a logical conjunction (AND) for a list of query conditions by separating the conditions with a comma in the conditions document.

```python
cursor = db.restaurants.find({"cuisine": "Italian", "address.zipcode": "10075"})
```

In [28]:
# TODO: Find all courses from Frank Habermann in the second semester
# and print the title and the semester

cursor = db.courses.find({"semester":2,"lecturer.name":"Frank Habermann"}, {'title',"semester"})
for document in cursor:
    pprint(document)

{'_id': ObjectId('628e4facb49f753ffdf81dab'),
 'semester': 2,
 'title': 'Business Process Integration Lab'}

## Logical OR

You can specify a logical disjunction (OR) for a list of query conditions by using the $or query operator.

```python
cursor = db.restaurants.find({"$or": [{"cuisine": "Italian"}, {"address.zipcode": "10075"}]})
```

In [34]:
# TODO: Find all courses from Frank Habermann or Markus Löcher
# and print the title and the semester

cursor = db.courses.find({"$or": [{"lecturer.name":"Markus Löcher"},{"lecturer.name":"Frank Habermann"}]}, {'title',"semester"})
for document in cursor:
    pprint(document)

{'_id': ObjectId('628e4facb49f753ffdf81da5'),
 'semester': 1,
 'title': 'Data Science'}
{'_id': ObjectId('628e4facb49f753ffdf81da7'),
 'semester': 1,
 'title': 'Business Process Management'}
{'_id': ObjectId('628e4facb49f753ffdf81da9'),
 'semester': 2,
 'title': 'Text, Web and Social Media Analytics Lab'}
{'_id': ObjectId('628e4facb49f753ffdf81dab'),
 'semester': 2,
 'title': 'Business Process Integration Lab'}

## Greater than, Less than

MongoDB provides operators to specify query conditions, such as comparison operators. Query conditions using operators generally have the following form:
```python
{ <field1>: { <operator1>: <value1> } }
```

Greater Than Operator (`$gt`). Query for documents whose grades array contains an embedded document with a field score greater than 30.

```python
cursor = db.restaurants.find({"grades.score": {"$gt": 30}})
```

Less Than Operator (`$lt`). Query for documents whose grades array contains an embedded document with a field score less than 10.

```python
cursor = db.restaurants.find({"grades.score": {"$lt": 10}})
```

In [38]:
# TODO: Find all courses in semester greater than 1
# and print the title and the semester

cursor = db.courses.find({"semester": {"$gt":1}}, {'title',"semester"})
for document in cursor:
    pprint(document)

{'_id': ObjectId('628e4facb49f753ffdf81da9'),
 'semester': 2,
 'title': 'Text, Web and Social Media Analytics Lab'}
{'_id': ObjectId('628e4facb49f753ffdf81daa'),
 'semester': 2,
 'title': 'Enterprise Architectures for Big Data'}
{'_id': ObjectId('628e4facb49f753ffdf81dab'),
 'semester': 2,
 'title': 'Business Process Integration Lab'}
{'_id': ObjectId('628e4facb49f753ffdf81dac'),
 'semester': 2,
 'title': 'IT-Security and Privacy'}
{'_id': ObjectId('628e4facb49f753ffdf81dad'),
 'semester': 2,
 'title': 'Research Methods'}

## Counting

`count_documents()` works like `find()` but returns the number of matched documents-

In [79]:
# TODO: How many courses are in the second semester?
db.courses.count_documents({"semester": 2})

0

# Downloading Nobel Prize Winners with an API and storing them in MongoDB

![](https://upload.wikimedia.org/wikipedia/en/e/ed/Nobel_Prize.png)
The Nobel Prize offers a Web API https://nobelprize.readme.io/docs/prize

Because the API is giving us JSON and MongoDB is able to store documents in a JSON-like format, using a document database like MongoDB seems like a good fit to store the results of the API.  You can get all laureates at http://api.nobelprize.org/v1/laureate.json and all prizes at http://api.nobelprize.org/v1/prize.json

We will just download all laureates and prizes and store them in MongoDB!

In [39]:
# Create local "nobel" database on the fly 
db = client["nobel"]
db.prizes.drop()
db.laureates.drop()
# API documented at https://nobelprize.readme.io/docs/prize 
for collection_name in ["prizes", "laureates"]:
    singular = collection_name[:-1] # the API uses singular
    response = requests.get( "http://api.nobelprize.org/v1/{}.json".format(singular)) 
    documents = response.json()[collection_name] 
    # Create collections on the fly 
    db[collection_name].insert_many(documents)

In [40]:
pprint(db.laureates.find_one())

{'_id': ObjectId('628e5c21b49f753ffdf82041'),
 'born': '1845-03-27',
 'bornCity': 'Lennep (now Remscheid)',
 'bornCountry': 'Prussia (now Germany)',
 'bornCountryCode': 'DE',
 'died': '1923-02-10',
 'diedCity': 'Munich',
 'diedCountry': 'Germany',
 'diedCountryCode': 'DE',
 'firstname': 'Wilhelm Conrad',
 'gender': 'male',
 'id': '1',
 'prizes': [{'affiliations': [{'city': 'Munich',
                               'country': 'Germany',
                               'name': 'Munich University'}],
             'category': 'physics',
             'motivation': '"in recognition of the extraordinary services he '
                           'has rendered by the discovery of the remarkable '
                           'rays subsequently named after him"',
             'share': '1',
             'year': '1901'}],
 'surname': 'Röntgen'}

In [45]:
# TODO: Print the first name of the first document
db.laureates.find_one({'id': '1'},{"firstname"})

{'_id': ObjectId('628e5c21b49f753ffdf82041'), 'firstname': 'Wilhelm Conrad'}

With `count_documents` you can count the number of matching documents.

In [49]:
# How many female laureates exists? 
pprint(db.laureates.count_documents({"gender":"female"}))

58

With the `$regex` function you can use a regular expression. `distinct` list only all distinct entries.

In [ ]:
db.laureates.distinct("bornCountry", {"bornCountry": {"$regex": "Germany"}})

['Prussia (now Germany)',
 'Hesse-Kassel (now Germany)',
 'Germany',
 'Schleswig (now Germany)',
 'Germany (now Poland)',
 'Germany (now France)',
 'West Germany (now Germany)',
 'Bavaria (now Germany)',
 'Germany (now Russia)',
 'Mecklenburg (now Germany)',
 'W&uuml;rttemberg (now Germany)',
 'East Friesland (now Germany)']

In [51]:
# TODO: How many laureates are from Germany?
pprint(db.laureates.count_documents({"bornCountry": {"$regex": "Germany"}}))

97

In [64]:
# TODO: Find all physics nobel laureates that are from Germany
# print the year of the first prize, the first name, and surename

cursor = db.laureates.find({"bornCountry": {"$regex": "Germany"}}, {"firstname","surname"})
for document in cursor:
    pprint(document)

{'_id': ObjectId('628e5c21b49f753ffdf82041'),
 'firstname': 'Wilhelm Conrad',
 'surname': 'Röntgen'}
{'_id': ObjectId('628e5c21b49f753ffdf8204d'),
 'firstname': 'Ferdinand',
 'surname': 'Braun'}
{'_id': ObjectId('628e5c21b49f753ffdf82052'),
 'firstname': 'Max',
 'surname': 'von Laue'}
{'_id': ObjectId('628e5c21b49f753ffdf82056'),
 'firstname': 'Max',
 'surname': 'Planck'}
{'_id': ObjectId('628e5c21b49f753ffdf82057'),
 'firstname': 'Johannes',
 'surname': 'Stark'}
{'_id': ObjectId('628e5c21b49f753ffdf82059'),
 'firstname': 'Albert',
 'surname': 'Einstein'}
{'_id': ObjectId('628e5c21b49f753ffdf8205d'),
 'firstname': 'James',
 'surname': 'Franck'}
{'_id': ObjectId('628e5c21b49f753ffdf8205e'),
 'firstname': 'Gustav',
 'surname': 'Hertz'}
{'_id': ObjectId('628e5c21b49f753ffdf82065'),
 'firstname': 'Werner',
 'surname': 'Heisenberg'}
{'_id': ObjectId('628e5c21b49f753ffdf8206f'),
 'firstname': 'Otto',
 'surname': 'Stern'}
{'_id': ObjectId('628e5c21b49f753ffdf8207c'),
 'firstname': 'Max',
 'surname': 'Born'}
{'_id': ObjectId('628e5c21b49f753ffdf8207d'),
 'firstname': 'Walther',
 'surname': 'Bothe'}
{'_id': ObjectId('628e5c21b49f753ffdf8207f'),
 'firstname': 'Polykarp',
 'surname': 'Kusch'}
{'_id': ObjectId('628e5c21b49f753ffdf8208b'),
 'firstname': 'Rudolf',
 'surname': 'Mössbauer'}
{'_id': ObjectId('628e5c21b49f753ffdf8208e'),
 'firstname': 'Maria',
 'surname': 'Goeppert Mayer'}
{'_id': ObjectId('628e5c21b49f753ffdf8208f'),
 'firstname': 'J. Hans D.',
 'surname': 'Jensen'}
{'_id': ObjectId('628e5c21b49f753ffdf82096'),
 'firstname': 'Alfred',
 'surname': 'Kastler'}
{'_id': ObjectId('628e5c21b49f753ffdf82097'),
 'firstname': 'Hans',
 'surname': 'Bethe'}
{'_id': ObjectId('628e5c21b49f753ffdf820ad'),
 'firstname': 'Arno',
 'surname': 'Penzias'}
{'_id': ObjectId('628e5c21b49f753ffdf820bd'),
 'firstname': 'Ernst',
 'surname': 'Ruska'}
{'_id': ObjectId('628e5c21b49f753ffdf820be'),
 'firstname': 'Gerd',
 'surname': 'Binnig'}
{'_id': ObjectId('628e5c21b49f753ffdf820c0'),
 'firstname': 'J. Georg',
 'surname': 'Bednorz'}
{'_id': ObjectId('628e5c21b49f753ffdf820c4'),
 'firstname': 'Jack',
 'surname': 'Steinberger'}
{'_id': ObjectId('628e5c21b49f753ffdf820c6'),
 'firstname': 'Hans G.',
 'surname': 'Dehmelt'}
{'_id': ObjectId('628e5c21b49f753ffdf820c7'),
 'firstname': 'Wolfgang',
 'surname': 'Paul'}
{'_id': ObjectId('628e5c21b49f753ffdf820da'),
 'firstname': 'Horst L.',
 'surname': 'Störmer'}
{'_id': ObjectId('628e5c21b49f753ffdf820df'),
 'firstname': 'Emil',
 'surname': 'Fischer'}
{'_id': ObjectId('628e5c21b49f753ffdf820e2'),
 'firstname': 'Adolf',
 'surname': 'von Baeyer'}
{'_id': ObjectId('628e5c21b49f753ffdf820e4'),
 'firstname': 'Eduard',
 'surname': 'Buchner'}
{'_id': ObjectId('628e5c21b49f753ffdf820e7'),
 'firstname': 'Otto',
 'surname': 'Wallach'}
{'_id': ObjectId('628e5c21b49f753ffdf820ec'),
 'firstname': 'Richard',
 'surname': 'Willstätter'}
{'_id': ObjectId('628e5c21b49f753ffdf820f4'),
 'firstname': 'Heinrich',
 'surname': 'Wieland'}
{'_id': ObjectId('628e5c21b49f753ffdf820f5'),
 'firstname': 'Adolf',
 'surname': 'Windaus'}
{'_id': ObjectId('628e5c21b49f753ffdf820f7'),
 'firstname': 'Hans',
 'surname': 'von Euler-Chelpin'}
{'_id': ObjectId('628e5c21b49f753ffdf820f8'),
 'firstname': 'Hans',
 'surname': 'Fischer'}
{'_id': ObjectId('628e5c21b49f753ffdf820f9'),
 'firstname': 'Carl',
 'surname': 'Bosch'}
{'_id': ObjectId('628e5c21b49f753ffdf820fa'),
 'firstname': 'Friedrich',
 'surname': 'Bergius'}
{'_id': ObjectId('628e5c21b49f753ffdf82103'),
 'firstname': 'Adolf',
 'surname': 'Butenandt'}
{'_id': ObjectId('628e5c21b49f753ffdf82106'),
 'firstname': 'Otto',
 'surname': 'Hahn'}
{'_id': ObjectId('628e5c21b49f753ffdf8210e'),
 'firstname': 'Otto',
 'surname': 'Diels'}
{'_id': ObjectId('628e5c21b49f753ffdf82114'),
 'firstname': 'Hermann',
 'surname': 'Staudinger'}
{'_id': ObjectId('628e5c21b49f753ffdf82120'),
 'firstname': 'Karl',
 'surname': 'Ziegler'}
{'_id': ObjectId('628e5c21b49f753ffdf82125'),
 'firstname': 'Manfred',
 'surname': 'Eigen'}
{'_id': ObjectId('628e5c21b49f753ffdf8212c'),
 'firstname': 'Gerhard',
 'surname': 'Herzberg'}
{'_id': ObjectId('628e5c21b49f753ffdf82130'),
 'firstname': 'Ernst Otto',
 'surname': 'Fischer'}
{'_id': ObjectId('628e5c21b49f753ffdf82139'),
 'firstname': 'Georg',
 'surname': 'Wittig'}
{'_id': ObjectId('628e5c21b49f753ffdf82145'),
 'firstname': 'John C.',
 'surname': 'Polanyi'}
{'_id': ObjectId('628e5c21b49f753ffdf82149'),
 'firstname': 'Johann',
 'surname': 'Deisenhofer'}
{'_id': ObjectId('628e5c21b49f753ffdf8214a'),
 'firstname': 'Robert',
 'surname': 'Huber'}
{'_id': ObjectId('628e5c21b49f753ffdf8214b'),
 'firstname': 'Hartmut',
 'surname': 'Michel'}
{'_id': ObjectId('628e5c21b49f753ffdf82164'),
 'firstname': 'Robert',
 'surname': 'Koch'}
{'_id': ObjectId('628e5c21b49f753ffdf8216b'),
 'firstname': 'Albrecht',
 'surname': 'Kossel'}
{'_id': ObjectId('628e5c21b49f753ffdf82173'),
 'firstname': 'Otto',
 'surname': 'Meyerhof'}
{'_id': ObjectId('628e5c21b49f753ffdf8217d'),
 'firstname': 'Otto',
 'surname': 'Warburg'}
{'_id': ObjectId('628e5c21b49f753ffdf82184'),
 'firstname': 'Hans',
 'surname': 'Spemann'}
{'_id': ObjectId('628e5c21b49f753ffdf82186'),
 'firstname': 'Otto',
 'surname': 'Loewi'}
{'_id': ObjectId('628e5c21b49f753ffdf82189'),
 'firstname': 'Gerhard',
 'surname': 'Domagk'}
{'_id': ObjectId('628e5c21b49f753ffdf8218f'),
 'firstname': 'Ernst B.',
 'surname': 'Chain'}
{'_id': ObjectId('628e5c21b49f753ffdf8219d'),
 'firstname': 'Hans',
 'surname': 'Krebs'}
{'_id': ObjectId('628e5c21b49f753ffdf8219e'),
 'firstname': 'Fritz',
 'surname': 'Lipmann'}
{'_id': ObjectId('628e5c21b49f753ffdf821a4'),
 'firstname': 'Werner',
 'surname': 'Forssmann'}
{'_id': ObjectId('628e5c21b49f753ffdf821b5'),
 'firstname': 'Konrad',
 'surname': 'Bloch'}
{'_id': ObjectId('628e5c21b49f753ffdf821b6'),
 'firstname': 'Feodor',
 'surname': 'Lynen'}
{'_id': ObjectId('628e5c21b49f753ffdf821c2'),
 'firstname': 'Max',
 'surname': 'Delbrück'}
{'_id': ObjectId('628e5c21b49f753ffdf821c5'),
 'firstname': 'Sir Bernard',
 'surname': 'Katz'}
{'_id': ObjectId('628e5c21b49f753ffdf821e9'),
 'firstname': 'Georges J.F.',
 'surname': 'Köhler'}
{'_id': ObjectId('628e5c21b49f753ffdf821f7'),
 'firstname': 'Erwin',
 'surname': 'Neher'}
{'_id': ObjectId('628e5c21b49f753ffdf821f8'),
 'firstname': 'Bert',
 'surname': 'Sakmann'}
{'_id': ObjectId('628e5c21b49f753ffdf82200'),
 'firstname': 'Christiane',
 'surname': 'Nüsslein-Volhard'}
{'_id': ObjectId('628e5c21b49f753ffdf82208'),
 'firstname': 'Günter',
 'surname': 'Blobel'}
{'_id': ObjectId('628e5c21b49f753ffdf82225'),
 'firstname': 'Gustav',
 'surname': 'Stresemann'}
{'_id': ObjectId('628e5c21b49f753ffdf82227'),
 'firstname': 'Ludwig',
 'surname': 'Quidde'}
{'_id': ObjectId('628e5c21b49f753ffdf8222e'),
 'firstname': 'Carl',
 'surname': 'von Ossietzky'}
{'_id': ObjectId('628e5c21b49f753ffdf8223a'),
 'firstname': 'Albert',
 'surname': 'Schweitzer'}
{'_id': ObjectId('628e5c21b49f753ffdf82248'),
 'firstname': 'Willy',
 'surname': 'Brandt'}
{'_id': ObjectId('628e5c21b49f753ffdf82249'),
 'firstname': 'Henry',
 'surname': 'Kissinger'}
{'_id': ObjectId('628e5c21b49f753ffdf82270'),
 'firstname': 'Theodor',
 'surname': 'Mommsen'}
{'_id': ObjectId('628e5c21b49f753ffdf82277'),
 'firstname': 'Rudolf',
 'surname': 'Eucken'}
{'_id': ObjectId('628e5c21b49f753ffdf82279'),
 'firstname': 'Paul',
 'surname': 'Heyse'}
{'_id': ObjectId('628e5c21b49f753ffdf8228b'),
 'firstname': 'Thomas',
 'surname': 'Mann'}
{'_id': ObjectId('628e5c21b49f753ffdf82297'),
 'firstname': 'Hermann',
 'surname': 'Hesse'}
{'_id': ObjectId('628e5c21b49f753ffdf822ac'),
 'firstname': 'Nelly',
 'surname': 'Sachs'}
{'_id': ObjectId('628e5c21b49f753ffdf822b2'),
 'firstname': 'Heinrich',
 'surname': 'Böll'}
{'_id': ObjectId('628e5c21b49f753ffdf822f3'),
 'firstname': 'Reinhard',
 'surname': 'Selten'}
{'_id': ObjectId('628e5c21b49f753ffdf82301'),
 'firstname': 'Herbert',
 'surname': 'Kroemer'}
{'_id': ObjectId('628e5c21b49f753ffdf8230d'),
 'firstname': 'Wolfgang',
 'surname': 'Ketterle'}
{'_id': ObjectId('628e5c21b49f753ffdf82340'),
 'firstname': 'Theodor W.',
 'surname': 'Hänsch'}
{'_id': ObjectId('628e5c21b49f753ffdf82346'),
 'firstname': 'Robert J.',
 'surname': 'Aumann'}
{'_id': ObjectId('628e5c21b49f753ffdf82357'),
 'firstname': 'Gerhard',
 'surname': 'Ertl'}
{'_id': ObjectId('628e5c21b49f753ffdf8235e'),
 'firstname': 'Harald',
 'surname': 'zur Hausen'}
{'_id': ObjectId('628e5c21b49f753ffdf8239b'),
 'firstname': 'Thomas C.',
 'surname': 'Südhof'}
{'_id': ObjectId('628e5c21b49f753ffdf823cc'),
 'firstname': 'Rainer',
 'surname': 'Weiss'}
{'_id': ObjectId('628e5c21b49f753ffdf823d0'),
 'firstname': 'Joachim',
 'surname': 'Frank'}
{'_id': ObjectId('628e5c21b49f753ffdf823e7'),
 'firstname': 'John',
 'surname': 'Goodenough'}
{'_id': ObjectId('628e5c21b49f753ffdf823f4'),
 'firstname': 'Reinhard',
 'surname': 'Genzel'}
{'_id': ObjectId('628e5c21b49f753ffdf823ff'),
 'firstname': 'Klaus',
 'surname': 'Hasselmann'}
{'_id': ObjectId('628e5c21b49f753ffdf82401'),
 'firstname': 'Benjamin',
 'surname': 'List'}

In [69]:
# TODO: find and print the document for "Malala" (firstname)

pprint(db.laureates.find_one({"firstname":"Malala"}))

{'_id': ObjectId('628e5c21b49f753ffdf823b1'),
 'born': '1997-07-12',
 'bornCity': 'Mingora',
 'bornCountry': 'Pakistan',
 'bornCountryCode': 'PK',
 'died': '0000-00-00',
 'firstname': 'Malala',
 'gender': 'female',
 'id': '914',
 'prizes': [{'affiliations': [[]],
             'category': 'peace',
             'motivation': '"for their struggle against the suppression of '
                           'children and young people and for the right of all '
                           'children to education"',
             'share': '2',
             'year': '2014'}],
 'surname': 'Yousafzai'}

## Sort()

With `sort()` you can sort the list of documents. The parameter of sort is a list of sorting tuples. Each tuple is a value and an integer value 1 or -1 which states whether the collection to be sorted in ascending (1) or descending (-1) order.

Sort all restaurants according to the grade in ascending order.
```python
cursor = db.restaurants.find().sort([("grades.grade", 1)])
```

In [72]:
# TODO: Find only female nobel laureates 
# and sort them according the the prize year in ascending order
# print year of the first prize, firstname, and surename

cursor = db.laureates.find({"gender":"female"}, {"prizes.year","firstname","surname"}).sort([("prizes.year",1)])
for document in cursor:
    pprint(document)

{'_id': ObjectId('628e5c21b49f753ffdf82046'),
 'firstname': 'Marie',
 'prizes': [{'year': '1903'}, {'year': '1911'}],
 'surname': 'Curie'}
{'_id': ObjectId('628e5c21b49f753ffdf8220f'),
 'firstname': 'Bertha',
 'prizes': [{'year': '1905'}],
 'surname': 'von Suttner'}
{'_id': ObjectId('628e5c21b49f753ffdf82278'),
 'firstname': 'Selma',
 'prizes': [{'year': '1909'}],
 'surname': 'Lagerlöf'}
{'_id': ObjectId('628e5c21b49f753ffdf82288'),
 'firstname': 'Grazia',
 'prizes': [{'year': '1926'}],
 'surname': 'Deledda'}
{'_id': ObjectId('628e5c21b49f753ffdf8228a'),
 'firstname': 'Sigrid',
 'prizes': [{'year': '1928'}],
 'surname': 'Undset'}
{'_id': ObjectId('628e5c21b49f753ffdf8222a'),
 'firstname': 'Jane',
 'prizes': [{'year': '1931'}],
 'surname': 'Addams'}
{'_id': ObjectId('628e5c21b49f753ffdf820fe'),
 'firstname': 'Irène',
 'prizes': [{'year': '1935'}],
 'surname': 'Joliot-Curie'}
{'_id': ObjectId('628e5c21b49f753ffdf82293'),
 'firstname': 'Pearl',
 'prizes': [{'year': '1938'}],
 'surname': 'Buck'}
{'_id': ObjectId('628e5c21b49f753ffdf82296'),
 'firstname': 'Gabriela',
 'prizes': [{'year': '1945'}],
 'surname': 'Mistral'}
{'_id': ObjectId('628e5c21b49f753ffdf82233'),
 'firstname': 'Emily Greene',
 'prizes': [{'year': '1946'}],
 'surname': 'Balch'}
{'_id': ObjectId('628e5c21b49f753ffdf82193'),
 'firstname': 'Gerty',
 'prizes': [{'year': '1947'}],
 'surname': 'Cori'}
{'_id': ObjectId('628e5c21b49f753ffdf8208e'),
 'firstname': 'Maria',
 'prizes': [{'year': '1963'}],
 'surname': 'Goeppert Mayer'}
{'_id': ObjectId('628e5c21b49f753ffdf82122'),
 'firstname': 'Dorothy Crowfoot',
 'prizes': [{'year': '1964'}],
 'surname': 'Hodgkin'}
{'_id': ObjectId('628e5c21b49f753ffdf822ac'),
 'firstname': 'Nelly',
 'prizes': [{'year': '1966'}],
 'surname': 'Sachs'}
{'_id': ObjectId('628e5c21b49f753ffdf8224e'),
 'firstname': 'Betty',
 'prizes': [{'year': '1976'}],
 'surname': 'Williams'}
{'_id': ObjectId('628e5c21b49f753ffdf8224f'),
 'firstname': 'Mairead',
 'prizes': [{'year': '1976'}],
 'surname': 'Corrigan'}
{'_id': ObjectId('628e5c21b49f753ffdf821d8'),
 'firstname': 'Rosalyn',
 'prizes': [{'year': '1977'}],
 'surname': 'Yalow'}
{'_id': ObjectId('628e5c21b49f753ffdf82253'),
 'firstname': 'Anjezë Gonxhe',
 'prizes': [{'year': '1979'}],
 'surname': 'Bojaxhiu'}
{'_id': ObjectId('628e5c21b49f753ffdf82255'),
 'firstname': 'Alva',
 'prizes': [{'year': '1982'}],
 'surname': 'Myrdal'}
{'_id': ObjectId('628e5c21b49f753ffdf821e7'),
 'firstname': 'Barbara',
 'prizes': [{'year': '1983'}],
 'surname': 'McClintock'}
{'_id': ObjectId('628e5c21b49f753ffdf821ee'),
 'firstname': 'Rita',
 'prizes': [{'year': '1986'}],
 'surname': 'Levi-Montalcini'}
{'_id': ObjectId('628e5c21b49f753ffdf821f1'),
 'firstname': 'Gertrude B.',
 'prizes': [{'year': '1988'}],
 'surname': 'Elion'}
{'_id': ObjectId('628e5c21b49f753ffdf8225f'),
 'firstname': 'Aung San Suu Kyi',
 'prizes': [{'year': '1991'}]}
{'_id': ObjectId('628e5c21b49f753ffdf822c6'),
 'firstname': 'Nadine',
 'prizes': [{'year': '1991'}],
 'surname': 'Gordimer'}
{'_id': ObjectId('628e5c21b49f753ffdf82260'),
 'firstname': 'Rigoberta',
 'prizes': [{'year': '1992'}],
 'surname': 'Menchú Tum'}
{'_id': ObjectId('628e5c21b49f753ffdf822c8'),
 'firstname': 'Toni',
 'prizes': [{'year': '1993'}],
 'surname': 'Morrison'}
{'_id': ObjectId('628e5c21b49f753ffdf82200'),
 'firstname': 'Christiane',
 'prizes': [{'year': '1995'}],
 'surname': 'Nüsslein-Volhard'}
{'_id': ObjectId('628e5c21b49f753ffdf822cb'),
 'firstname': 'Wislawa',
 'prizes': [{'year': '1996'}],
 'surname': 'Szymborska'}
{'_id': ObjectId('628e5c21b49f753ffdf8226b'),
 'firstname': 'Jody',
 'prizes': [{'year': '1997'}],
 'surname': 'Williams'}
{'_id': ObjectId('628e5c21b49f753ffdf8232f'),
 'firstname': 'Shirin',
 'prizes': [{'year': '2003'}],
 'surname': 'Ebadi'}
{'_id': ObjectId('628e5c21b49f753ffdf82331'),
 'firstname': 'Linda B.',
 'prizes': [{'year': '2004'}],
 'surname': 'Buck'}
{'_id': ObjectId('628e5c21b49f753ffdf82338'),
 'firstname': 'Elfriede',
 'prizes': [{'year': '2004'}],
 'surname': 'Jelinek'}
{'_id': ObjectId('628e5c21b49f753ffdf82339'),
 'firstname': 'Wangari',
 'prizes': [{'year': '2004'}],
 'surname': 'Maathai'}
{'_id': ObjectId('628e5c21b49f753ffdf82358'),
 'firstname': 'Doris',
 'prizes': [{'year': '2007'}],
 'surname': 'Lessing'}
{'_id': ObjectId('628e5c21b49f753ffdf8235f'),
 'firstname': 'Françoise',
 'prizes': [{'year': '2008'}],
 'surname': 'Barré-Sinoussi'}
{'_id': ObjectId('628e5c21b49f753ffdf8236a'),
 'firstname': 'Elizabeth H.',
 'prizes': [{'year': '2009'}],
 'surname': 'Blackburn'}
{'_id': ObjectId('628e5c21b49f753ffdf8236b'),
 'firstname': 'Carol W.',
 'prizes': [{'year': '2009'}],
 'surname': 'Greider'}
{'_id': ObjectId('628e5c21b49f753ffdf82372'),
 'firstname': 'Ada E.',
 'prizes': [{'year': '2009'}],
 'surname': 'Yonath'}
{'_id': ObjectId('628e5c21b49f753ffdf82373'),
 'firstname': 'Herta',
 'prizes': [{'year': '2009'}],
 'surname': 'Müller'}
{'_id': ObjectId('628e5c21b49f753ffdf82375'),
 'firstname': 'Elinor',
 'prizes': [{'year': '2009'}],
 'surname': 'Ostrom'}
{'_id': ObjectId('628e5c21b49f753ffdf8238a'),
 'firstname': 'Ellen',
 'prizes': [{'year': '2011'}],
 'surname': 'Johnson Sirleaf'}
{'_id': ObjectId('628e5c21b49f753ffdf8238b'),
 'firstname': 'Leymah',
 'prizes': [{'year': '2011'}],
 'surname': 'Gbowee'}
{'_id': ObjectId('628e5c21b49f753ffdf8238c'),
 'firstname': 'Tawakkol',
 'prizes': [{'year': '2011'}],
 'surname': 'Karman'}
{'_id': ObjectId('628e5c21b49f753ffdf823a1'),
 'firstname': 'Alice',
 'prizes': [{'year': '2013'}],
 'surname': 'Munro'}
{'_id': ObjectId('628e5c21b49f753ffdf823a7'),
 'firstname': 'May-Britt',
 'prizes': [{'year': '2014'}],
 'surname': 'Moser'}
{'_id': ObjectId('628e5c21b49f753ffdf823b1'),
 'firstname': 'Malala',
 'prizes': [{'year': '2014'}],
 'surname': 'Yousafzai'}
{'_id': ObjectId('628e5c21b49f753ffdf823b5'),
 'firstname': 'Youyou',
 'prizes': [{'year': '2015'}],
 'surname': 'Tu'}
{'_id': ObjectId('628e5c21b49f753ffdf823bb'),
 'firstname': 'Svetlana',
 'prizes': [{'year': '2015'}],
 'surname': 'Alexievich'}
{'_id': ObjectId('628e5c21b49f753ffdf823d9'),
 'firstname': 'Donna',
 'prizes': [{'year': '2018'}],
 'surname': 'Strickland'}
{'_id': ObjectId('628e5c21b49f753ffdf823da'),
 'firstname': 'Frances H.',
 'prizes': [{'year': '2018'}],
 'surname': 'Arnold'}
{'_id': ObjectId('628e5c21b49f753ffdf823de'),
 'firstname': 'Nadia',
 'prizes': [{'year': '2018'}],
 'surname': 'Murad'}
{'_id': ObjectId('628e5c21b49f753ffdf823ea'),
 'firstname': 'Olga',
 'prizes': [{'year': '2018'}],
 'surname': 'Tokarczuk'}
{'_id': ObjectId('628e5c21b49f753ffdf823ee'),
 'firstname': 'Esther',
 'prizes': [{'year': '2019'}],
 'surname': 'Duflo'}
{'_id': ObjectId('628e5c21b49f753ffdf823f5'),
 'firstname': 'Andrea',
 'prizes': [{'year': '2020'}],
 'surname': 'Ghez'}
{'_id': ObjectId('628e5c21b49f753ffdf823f6'),
 'firstname': 'Emmanuelle',
 'prizes': [{'year': '2020'}],
 'surname': 'Charpentier'}
{'_id': ObjectId('628e5c21b49f753ffdf823f7'),
 'firstname': 'Jennifer A.',
 'prizes': [{'year': '2020'}],
 'surname': 'Doudna'}
{'_id': ObjectId('628e5c21b49f753ffdf823f8'),
 'firstname': 'Louise',
 'prizes': [{'year': '2020'}],
 'surname': 'Glück'}
{'_id': ObjectId('628e5c21b49f753ffdf82404'),
 'firstname': 'Maria',
 'prizes': [{'year': '2021'}],
 'surname': 'Ressa'}